#!/usr/bin/env ruby
# encoding: utf-8

$:.unshift File.dirname(__FILE__) + '/../library'
require 'blur'

options = {
  networks: [
    {
      hostname: "uplink.io",
      nickname: "meta-test2",
      channels: %w{#uplink},
        secure: true,
          port: 6697
    },
=begin
    {
      hostname: "irc.dk.quakenet.org",
      nickname: "meta-qnet",
      channels: %w{#warsow.na}
    }
=end
  ]
}

Blur.connect options do
  puts "==> Blur #{Blur::Version}"
end
