#!/usr/bin/env ruby
# encoding: utf-8

$:.unshift File.dirname(__FILE__) + '/../library'
require 'blur'

options = {
  networks: []
}

3.times do |i|
  test = {
    hostname: "uplink.io",
    nickname: "test-#{i}",
    channels: %w{#uplink}
  }

  options[:networks] << test
end

Blur.connect options do
  puts "==> Blur #{Blur::Version}"

  catch :connection_terminated do |network|
    Thread.new { sleep 2; network.connect }
  end
end
