#!/usr/bin/env ruby
# frozen_string_literal: true

require_relative '../library/blur'

require 'optparse'

options = {
  verbose: false,
  config_path: 'config.yml'
}

OptionParser.new do |opts|
  opts.banner = "Usage: #{$PROGRAM_NAME} [-c <config>] [-e <env>]"

  opts.separator ''
  opts.separator 'Specific options:'

  opts.on '-v', '--[no-]verbose', 'Enable verbose logging' do |verbose|
    options[:verbose] = verbose
  end

  opts.on '-c', '--config=PATH', 'Set the configuration file' do |config_path|
    options[:config_path] = config_path
  end

  opts.on '-eENV', '--environment=ENV', 'Environment to run in' do |environment|
    options[:environment] = environment
  end

  opts.on '-r', '--require LIBRARY', 'Require the LIBRARY before running' do |lib|
    require lib
  end

  opts.on_tail '-h', '--help', 'Show this message' do
    puts opts
    exit
  end
end.parse!

begin
  require 'blur'
rescue LoadError => e
  puts 'Ruby was unable to load the blur library!'
  puts
  puts "Please ensure that you've installed it using the following command:"
  puts 'gem install blur'
  raise e
end

puts "Blur #{Blur.version}"

config_path = File.expand_path options[:config_path]
puts "Loading configuration file `#{config_path}' .."

raise "Configuration file `#{config_path}' is not readable" unless File.readable? config_path

@client = Blur::Client.new options
@client.connect

# vim: syntax=ruby
