#!/usr/bin/env ruby
# encoding: utf-8

$:.unshift File.dirname(__FILE__) + '/../library'
require 'pulse'

options = {
  nickname: "meta",
  networks: ["irc.maero.dk:6667", "irc.maero.dk:6668"]
}

Pulse.connect options do
  puts "=> Pulse #{Pulse::Version}"

end
