#!/usr/bin/env ruby
# encoding: utf-8

$:.unshift File.dirname(__FILE__) + '/../library'
require 'pulse'

Pulse.connect hostname: 'irc.maero.dk' do
  catch :nickchange do |user, nick|
    puts "#{user.name} changed name to #{nick}"
  end
end
