name: Continuous Integration

on:
  pull_request:
    branches:
    - main

jobs:
  test:
    name: Test
    runs-on: ubuntu-latest
    steps:
    - name: Checkout source code
      uses: actions/checkout@v4
    - name: Setup Ruby
      uses: ruby/setup-ruby@d4526a55538b775af234ba4af27118ed6f8f6677 # v1.172.0
      with:
        bundler-cache: true # runs 'bundle install' and caches installed gems automatically
    - name: Run specs
      run: bundle exec rspec --format documentation
